### PR TITLE
Made CONTRIBUTING.md better and more informative

### PR DESCRIPTION
**Pull request by ritik-singh07**
Made contributing.md more informative and guiding for new comers, It will make it easy and efficient for both people participating to contribute here by reading it.

### CODE REVIEW

**Comment by codemaniac-sahil** [comment]
You did excellent @bloodmonk7

**Comment by codemaniac-sahil** [comment]
Would you please fix all my repository's contributing.md file.

**Comment by ritik-singh07** [comment]
Surely, Should I go with same format? @codemaniac-sahil

**Comment by codemaniac-sahil** [comment]
Yes @bloodmonk7

**Comment by ritik-singh07** [comment]
Ok I will get it done by today only

**Comment by codemaniac-sahil** [comment]
Not every repos, only those repos which have tags of hacktoberfest

**Comment by ritik-singh07** [comment]
Ok, I will do it right-now

**Pull request merged**
