### PR TITLE
#2: Added more info about weather and searching by pressing enter

### PR DESCRIPTION
**Pull request by PolisanTheEasyNick**
Added country name around entered city name
Added pressure information
Added humidity information
Added wind speed information
Added ability to start script when enter button is released
Changed names of variables from use, use1, use2 to more informative "cityName" and so on

### CODE REVIEW

**Comment by codemaniac-sahil** [comment]
@PolisanTheEasyNick  It's UI is crashing

**Comment by PolisanTheEasyNick** [comment]
@codemaniac-sahil Can you please describe it? Because in my local project it looks cool
image

**Comment by codemaniac-sahil** [comment]
Screenshot (23)
It is showing me like this

**Comment by PolisanTheEasyNick** [comment]
Looks like problem with gradient when page is scrollable. I will try to change size between information strings

**Comment by codemaniac-sahil** [comment]
@PolisanTheEasyNick you can also remove the gradient

**Comment by codemaniac-sahil** [comment]
Just make it appealing.

**Comment by codemaniac-sahil** [comment]
If you can modify the css of landing page then it will be great.

**Comment by PolisanTheEasyNick** [comment]
Added new commit, try this one

**Comment by codemaniac-sahil** [comment]
Now, It is looking great

**Comment by PolisanTheEasyNick** [comment]
Thank you :)

**Comment by codemaniac-sahil** [comment]
You did very well @PolisanTheEasyNick

**Pull request merged**
