### PR TITLE
changed landing UI

### PR DESCRIPTION
**Pull request by NayakPenguin**
I have changed the structure of the landing UI, please merge these then I will start working on the JS portion. 
Screenshot 2022-10-02 at 5 47 48 PM

### CODE REVIEW

**Comment by codemaniac-sahil** [comment]
May I know why you created top stories section

**Comment by NayakPenguin** [comment]
This is just for the top weather news section because otherwise, the UI was looking pretty empty.

**Comment by codemaniac-sahil** [comment]
Nice

**Comment by codemaniac-sahil** [comment]
Excellent work @Nayaker

**Comment by NayakPenguin** [comment]
Thanks for the appreciation means a lot.

**Comment by codemaniac-sahil** [comment]
Screenshot (28)
why I am getting this

**Comment by NayakPenguin** [comment]
I will have to change the UI after we enter a city

**Comment by NayakPenguin** [comment]
Will soon also start working on that aswell

**Comment by codemaniac-sahil** [comment]
yes

**Comment by NayakPenguin** [comment]
I will make an updated PR soon, please do check that. 
Screenshot 2022-10-02 at 6 53 14 PM

**Comment by codemaniac-sahil** [comment]
Okay

**Comment by codemaniac-sahil** [comment]
It should be responsive

**Comment by NayakPenguin** [comment]
Made the code site responsive, please check then I will raise the PR.
Screenshot 2022-10-02 at 7 10 57 PM
Screenshot 2022-10-02 at 7 11 03 PM
Screenshot 2022-10-02 at 7 12 39 PM

**Comment by codemaniac-sahil** [comment]
it's good

**Comment by codemaniac-sahil** [comment]
Did you send the PR.

**Comment by NayakPenguin** [comment]
Now I did

**Pull request merged**
